apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: rminz/grpc-server
      docker:
        dockerfile: Dockerfile
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  local:
    push: true